# -*- coding: utf-8 -*-
"""tasl1-b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jh3ZJVxPiF-3_9OtTktWKVlN0wmgmHpF
"""

#task1-b
from collections import defaultdict
input=open("/content/sample_data/input-1b","r")
n,m=map(int,input.readline().split())
graph=defaultdict(list)
for i in range(m):
  u,v,w=map(int,input.readline().split())
  graph[u].append((v,w))
adj=[]
for i in range(1,n+1):
  row = [str(i) + " :"]
  for j, w in graph[i]:
    row.append(" (" + str(j) + "," + str(w) + ")")
  adj.append("".join(row))
with open('/content/sample_data/output-1b', 'w') as f:
    for row in adj:
        f.write(row + "\n")