# -*- coding: utf-8 -*-
"""task6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jh3ZJVxPiF-3_9OtTktWKVlN0wmgmHpF
"""

#task6
ip_file=open('/content/sample_data/input-6','r')
ip_data=ip_file.readlines()
op_file=open('/content/sample_data/output-6','w')
R=int((ip_data[0].split(' '))[0])+1
C=int((ip_data[0].split(' '))[1])
r=1
adj={}
color={}
while r<R:
    c=0
    color[r]=[]
    while c<C:
       color[r].append(0)
       e=ip_data[r][c]
       if e=='#':
           adj[str([r])+str([c])]=[]
           pass
       else:
         rp,rn,cp,cn=None,None,None,None
         if R==2:
           pass
         else:
            if r==1:
               rn=(r+1,c)
            elif r==R-1:
               rp=(r-1,c)
            else:
               rp,rn=(r-1,c),(r+1,c)
         if C==1:
             pass
         else:
            if c==0:
                cn=(r,c+1)
            elif c==C-1:
                cp=(r,c-1)
            else:
                cp,cn=(r,c-1),(r,c+1)
         adj[str([r])+str([c])]=[rp,rn,cp,cn]
       c+=1
    r+=1

class DFS:
  def __init__(self,G,color,dl):
     self.dl=dl
     self.G=G
     self.color=color

  def dfs(self,u):
     if ip_data[u[0]][u[1]]=='D':
         self.dl.append('D')
     if self.G[str([u[0]])+str([u[1]])]==[]:
         self.color[u[0]][u[1]]=2
     else:
       self.color[u[0]][u[1]] = 1
       for v in self.G[str([u[0]])+str([u[1]])]:
          if v==None:
              pass
          elif self.color[v[0]][v[1]] == 0:
              DFS.dfs(self,v)

     color[u[0]][u[1]]=2

a=DFS(adj,color,[])
a.dfs((1,0))
count=[len(a.dl)]

for i in range(1,len(color)):
    if 0 in color[i]:
        for j in range(len(color[i])):
            if color[i][j]==0:
                b=DFS(adj,color,[])
                b.dfs((i,j))
                count.append(len(b.dl))

print(max(count),file=op_file)